repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  # General
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: destroyed-symlinks
  - id: check-symlinks
  - id: check-added-large-files
  # Syntax
  - id: check-toml
  - id: check-json
  - id: check-yaml
  - id: check-ast
  # Line endings
  - id: mixed-line-ending
  - id: trailing-whitespace

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: rst-backticks
  - id: rst-directive-colons
  - id: rst-inline-touching-normal

- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.16
  hooks:
  - id: validate-pyproject

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.5
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]

- repo: https://github.com/cpendery/asort
  rev: v0.1.3
  hooks:
  - id: asort

- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
  - id: black
