name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_server:
    name: Build server
    runs-on: ubuntu-22.04
    strategy:
        fail-fast: false
        matrix:
          targets:
            # Developer/GNU targets
            - aarch64-unknown-linux-gnu
            - x86_64-unknown-linux-gnu

            # Musl targets
            - aarch64-unknown-linux-musl
            - armv7-unknown-linux-musleabi
            - i686-unknown-linux-musl
            # - mips-unknown-linux-musl # Broken
            - x86_64-unknown-linux-musl

            # Windows targets
            - i686-pc-windows-gnu
            - x86_64-pc-windows-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build
        run: cd crates/bh_agent_server && cross build --target ${{ matrix.targets }}

  build_server_macos:
    name: Build server (macOS)
    runs-on: macos-12
    strategy:
        fail-fast: false
        matrix:
          targets:
            - aarch64-apple-darwin
            - x86_64-apple-darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install target
        run: rustup target add ${{ matrix.targets }}
      - name: Build
        run: cd crates/bh_agent_server && cargo build --target ${{ matrix.targets }}

  test_python:
    runs-on: ubuntu-22.04
    strategy:
        matrix:
            python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "pypy3.9", "pypy3.10"]
    name: Tests on Python ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install host binaries
        run: sudo apt-get update && sudo apt-get install -y busybox-static qemu-user-static
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build bh_agent_server x86_64-unknown-linux-musl
        run: cross build --target x86_64-unknown-linux-musl -p crates/bh_agent_server
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install binharness
        run: pip install -e .[dev]
      - name: Run pytest
        run: pytest
