name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
        matrix:
            python-version: ["3.8", "3.9", "3.10", "3.11"]
    name: Tests on Python ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install binharness
        run: pip install -e .[dev]
      - name: Run ruff
        run: ruff .
      - name: Run black
        run: black --check .
      - name: Run mypy
        run: mypy binharness
      - name: Run pytest
        run: pytest
