name: Publish
on:
  push:
    tags: "v*"

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  publish:
      name: Publish release
      needs: ci
      runs-on: ubuntu-22.04
      permissions:
        contents: write
        id-token: write
      steps:
        - name: Download artifacts
          uses: actions/download-artifact@v4
        - name: Make wheel dir
          run: mkdir dist
        - name: Move wheels
          run: mv *.whl dist && mv *.tar.gz dist
        - name: Make new release
          run: >
            gh release create ${{ github.ref_name }} \
              --repo ${{ github.repository }} \
              --generate-notes \
              $(find . -type f)
          env:
            GH_TOKEN: ${{ github.token }}
        - name: Publish package distributions to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
